### ISSUE TITLE
Module VERSION needs to be updated to 0.6.0

### ISSUE THREAD

**Issue by cschol** [stellare-modular/vcv-link#2]
`VERSION` in the `Makefile` needs to be updated to `0.6.0` before release. Three digits, no `dev` suffix. Thank you!

**Comment by sanderbaan** [comment]
@petertools can you take care of this?

**Comment by stellare-modular** [comment]
@cschol we use the dev suffix on feature branches so that it's clear is not a "released" version (usually build from master). I will remove "dev" just before merging the branch to master so that 0.6 compatible release will be versioned 0.6.0, as you suggested.
