### ISSUE TITLE
Support for VCV Rack 0.6.2c

### ISSUE THREAD

**Issue by mungewell** [stellare-modular/vcv-link#5]
New to VCV rack and can't see how to load Stellare Link plugin. Suspect that the versions do not align...
![stellare_link_version](https://user-images.githubusercontent.com/236907/50524293-d97d8980-0acc-11e9-826e-14826ab68883.png)

Can you please rebuild for current VCV Rack version. Thanks,
Simon

**Comment by sewpew** [comment]
+1 :)

**Comment by roommatejosh** [comment]
+2 :)

**Comment by stellare-modular** [comment]
Starting with version 0.6.2 Stellare Modular Link is available through VCV Rack's Plugin Manager!
